### ISSUE TITLE
No way to set inner drawable programmatically

### ISSUE THREAD

**Issue by ryust** [Adilhusen/circle-progress-ad-android-#2]
Title says it all. Really wanted to use the library programmatically, but looks like some methods were left out to do so.

**Comment by ryust** [comment]
Well, I was able to override the onDraw method to get my drawable in the progress circle, but no progress will show. I am also adding the widget programmatically to manually created views (not XML) and nothing seems to work.

It appears this library is limited on how the progress circle can be created and shown.

**Comment by ryust** [comment]
Got it to work... had to draw the bitmap first and then draw the progress overlay to see the progress.

**Comment by bacancy-adilhusen** [comment]
"Closes #2"

**Comment by bacancy-adilhusen** [comment]
> Got it to work... had to draw the bitmap first and then draw the progress overlay to see the progress.

Yes  you can use  > setAttributeResourceId() method

**Comment by ryust** [comment]
I saw the setAttributeResourceId() method, but it doesn't do what I wanted... setDrawable(myDrawable) without using a resource. I create drawables dynamically.

**Comment by hossein-rezaeian** [comment]
You should call postInvalidate()  method  in the setAttributeResourceId() method inside the AdCircleProgress class
